### ISSUE TITLE
Security question: Protection against use of ".."?

### ISSUE THREAD

**Issue by hartwork** [aasmpro/smart_web_share#2]
Hi!

I haven't tried it yet, but given the current code at https://github.com/aasmpro/djangosmartshare/blob/7369a5d09e873cd34202b2e2c511729b1a9f4d68/smartshare/urls.py#L4 ..
```python
urlpatterns = [
    path('', shared_locations, name='locations'),
    path('path<path:address>', location_detail, name='location_detail'),
    path('download<path:address>:<data_type>', download, name='download'),
    path('upload<path:address>', upload, name='upload'),
    path('makedir<path:address>', make_dir, name='makedir'),
    path('makefile<path:address>', make_file, name='makefile'),
    path('delete<path:address>:<data_type>', delete, name='delete')
]
```
and the documentation for `<path:...>` at https://docs.djangoproject.com/en/2.1/topics/http/urls/#path-converters I wonder: Would `foo/../../../../../var/lib/mysql/` pass through to the views as-is to `address`?

Best, Sebastian

**Comment by aasmpro** [comment]
Hi!
Sebastian, i had thought about such a situation before
Yes these kind of paths will get to the View too. so lets say we have shared directory `/home/aasmpro/` and the app urls start with `http://127.0.0.1:8000/path/`, so this directories are under `/home/aasmpro/` as example:
```
Pictures
Downloads
```
we navigate to the `Pictures`, the URL would be `http://127.0.0.1:8000/path/home/aasmpro/Pictures/`, if we try to add `../Dowloads/` to the URL, that would be `http://127.0.0.1:8000/path/home/aasmpro/Pictures/../Downloads/` we actually will navigate to the `/home/aasmpro/Dowloads/` and the `../` part of address will be cleared automatically. that works out of the box.

but if you try to access a location that it's not shared ( no matter even you are admin ) such `foo/../../../../../var/lib/mysql/` you will get an 404 error, as this path is not available.

what's your idea, is that good?

**Comment by hartwork** [comment]
Some folder may not be accessible but some may, e.g. `/tmp` would work.
We can have more `..` than segments to walk up in that string and walk up to root of the file system. If we go further, we stay at root (and that saves the attacker some guessing) Try: `( cd /usr/ && ls -l ../../../../../tmp )`.
I'd consider any address that contains `..` (after percent decoding, which Django does for us I think) an attack to be blocked, personally. if you you allow *some* `..`, things get more complex and harder to get secure.

**Comment by aasmpro** [comment]
actually any folder that is not an object of shared locations, would not be accessible, even `/tmp`.
imagine if you have shared only your home directory at `/home/aasmpro/` any other path before it at the root directory or even in the same `/home/` directory would not be accessible.
