### ISSUE TITLE
Security concern: Use of os.system

### ISSUE THREAD

**Issue by hartwork** [aasmpro/smart_web_share#3]
I find this code at https://github.com/aasmpro/djangosmartshare/blob/c72ebe87670818b633de55b81c691c33bc51bb92/smartshare/utils.py#L21:
```python
def handle_delete(address, data_type):
    try:
        system("rm -rf {}".format(address))
    except:
        pass
```
For every path leading to `handle_delete`, has been made sure that `address` is free of quotes and spaces? If you avoid `shutil.rmtree` for speed(?), `subprocess.call(['rm', address])` would be more safe, at least in that regard.

Best, Sebastian

**Comment by aasmpro** [comment]
yes you are right that should be changed.
but if you try to delete a file in a location that is not shared, you will get 404, also deleting a file that need sudo permission, even if you are admin, will not work.
